# Generated by Django 4.1.13 on 2023-11-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_feed_image_homepageauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
