# Generated by Django 4.1.13 on 2023-11-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='feed_image',
        ),
    ]
