# Generated by Django 4.1.13 on 2023-11-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_feed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='published_date',
        ),
        migrations.DeleteModel(
            name='HomePageAuthor',
        ),
    ]
